### PR TITLE
Add support for auto-complete like behavior

### PR DESCRIPTION
**Pull request by jojojames**
Added company-ac-frontend to mimic auto-complete's delayed popup.

Added company-ac-complete to mimic (approximation) auto-complete's tab behavior.

Added convenience method company-ac-setup to approximate similar
auto-complete behavior without user intervention.

Notes: (Mostly referencing below issue 123)
- Seemed like the feature was never merged in, I pulled in @kencoken's changes and added some more changes (approximating auto-complete's behavior) to bring it to a finish. The naming change recommendations were done as well as pushing the timer cancellation to the precommand.

- From the issue thread, looks like it was might be better to add the additional functionality to the preexisting frontend. I think splitting the frontend out is cleaner and easier to implement (for me anyways).

- Tried my best to put code where it should be but it could possibly use some improvements.

- Not sure if company-tooltip-visible is needed but I wasn't able to find an easy way to check if the tooltip was currently visible.

- I think the auto-complete behavior might still defer slightly from this but it's a very close approximation and in some ways better (in my opinion).

- I can sign any licensing forms.

In reference to: 
https://github.com/company-mode/company-mode/issues/123

Other similar topics:
https://github.com/company-mode/company-mode/issues/216
https://github.com/company-mode/company-mode/issues/246#issuecomment-68538735

Lots of credit to: 
https://github.com/kencoken/company-mode/commit/bbbf217643b84471125ddfa7bdc98632656daa4f

### CODE REVIEW

**Comment by dgutov** [comment]
Hi! Thanks for the patch.

Two issues:

* Copyright. Would @kencoken be willing to sign the necessary papers as well?

* Names like `company-ac-frontend` are not good enough, and "behave similarly to auto-complete mode" is not a great description. Basically, I'd like to see descriptive names and docstrings that do not mention `auto-complete-mode`. `company-ac-setup` also seems better suited for the wiki.

On a minor note, please don't end commit message summary with a period, and use the imperative voice. See here for the examples and longer explanation: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by jojojames** [comment]
- Copyright. How should we move forward if @kencoken is not available? I guess implementing the delayed popup code another way is not out of question.
- Other Points. I'll make those changes when I can. What would you suggest for the frontend's name? 

I'll edit the wiki here https://github.com/company-mode/company-mode/wiki/Switching-from-AC and add an entry for company-ac-setup once we hash out all the issues.

**Comment by dgutov** [comment]
> I guess implementing the delayed popup code another way is not out of question.

Right. This code is not hugely essential, so an implementation that looks reasonably different should suffice.

> What would you suggest for the frontend's name?

I don't have a particular name in mind, but I gave some related suggestions in the first issue you've linked to.

**Comment by jojojames** [comment]
I modified company-pseudo-tooltip-frontend and added the timer code there. It hooks onto company-tooltip-idle-delay being non-nil before triggering the timer logic.

Otherwise, the logic seems straightforward. If the timer is non nil by the time the post command is hit, it means the timer has elapsed. If it's nil, that means the user pressed another key during that time period cancelling the timer.

Setting a default non-nil value on company-tooltip-idle-delay does break test company-pseudo-tooltip-does-not-get-displaced (makes sense, since the overlay count will be off in the test's instance now). I'm wondering how you'd update the test in this case. (Setting the default to be nil works fine with me too since that's going to be the standard case anyway.)

    (defun company-pseudo-tooltip-frontend (command)
      "`company-mode' frontend similar to a tooltip but based on overlays."
      (cl-case command
        (pre-command
         (company-pseudo-tooltip-hide-temporarily)
         (when (and company-tooltip-idle-delay company-tooltip-timer)
           (cancel-timer company-tooltip-timer)
           (setq company-tooltip-timer nil)))
        (post-command
         (if (and company-tooltip-idle-delay
                  (not company-tooltip-timer)
                  (not (overlayp company-pseudo-tooltip-overlay)))
             (setq company-tooltip-timer
                   (run-with-timer company-tooltip-idle-delay nil
                                   'company-pseudo-tooltip-frontend
                                   'post-command))
           (unless (when (overlayp company-pseudo-tooltip-overlay)
                     (let* ((ov company-pseudo-tooltip-overlay)
                            (old-height (overlay-get ov 'company-height))
                            (new-height (company--pseudo-tooltip-height)))
                       (and
                        (>= (* old-height new-height) 0)
                        (>= (abs old-height) (abs new-height))
                        (equal (company-pseudo-tooltip-guard)
                               (overlay-get ov 'company-guard)))))
             ;; Redraw needed.
             (company-pseudo-tooltip-show-at-point (point) (length company-prefix))
             (overlay-put company-pseudo-tooltip-overlay
                          'company-guard (company-pseudo-tooltip-guard)))
           (company-pseudo-tooltip-unhide)))
        (hide (company-pseudo-tooltip-hide)
              (setq company-tooltip-offset 0))
        (update (when (overlayp company-pseudo-tooltip-overlay)
                  (company-pseudo-tooltip-edit company-selection)))))

**Comment by dgutov** [comment]
Actually, I like the "separate frontend" solution better.

**Comment by jojojames** [comment]
I think I made most of the changes requested. Let me know if you had any other concerns.

Travis build seems to have failed with the last commit. I'm not sure why that is. (The change seems pretty straightforward for the failing commit)

**Comment by dgutov** [comment]
Thanks, looks good. I think we can consider Ken's contribution to be below the "tiny change" limit now. Please see the copyright assignment instructions here: http://orgmode.org/cgit.cgi/org-mode.git/plain/request-assign-future.txt

> Travis build seems to have failed with the last commit.

It was just Travis being flaky. I've restarted it, and it's green now.

**Comment by jojojames** [comment]
I've received the copyright assignment.

**Comment by dgutov** [comment]
Looking over the code, `company-complete-selection-or-select-next-if-tooltip-visible` is iffy:

* Should it be called `company-select-next-if-tooltip-visible-or-complete-selection` instead?
* The docstring's first sentence should be imperative, short, and meaningful (like the second one here, but shorter).
* It seems like you want the behavior from #526 in the "other" case anyway. Considering it's imperfect, do you still use a command like that?

Also, shouldn't `company-pseudo-tooltip-frontend-with-delay` be wrapping `company-pseudo-tooltip-unless-just-one-frontend` instead? Showing the tooltip for just one completion seems counter-productive.

**Comment by jojojames** [comment]
- I can make the name change to company-select-next-if-tooltip-visible-or-complete-selection as well as tightening up the docstring.

 - I'm not sure what the 'other' case is in this case though I do use YCM when I'm using vim. 

YCM's autocompletion behavior is nice but I think it has its own tradeoffs (namely due to lack of preview completion).

 - I'm using that completion (company-complete-selection-or-select-next-if-tooltip-visible) these days and it's working perfectly for me.

 - You're right about wrapping company-pseudo-tooltip-unless-just-one-frontend instead. I'll get that changed.

**Comment by dgutov** [comment]
> I'm not sure what the 'other' case is in this case though

The "other" case is when the tooltip is visible, and TAB iterates between completions.

With YCM, you can press TAB a few times, and then continue typing. The completion is inserted automatically before that.

In Company, you'd have press RET first. Or are you using `company-auto-complete`, too?

**Comment by jojojames** [comment]
Yeah, I hook company-auto-complete to whether or not the tooltip is visible which ends up with very sane completion behavior in my opinion.

 (defun company-ac-setup ()
    "Sets up company to behave similarly to auto-complete mode."
    (setq company-require-match nil)
    (setq company-auto-complete #'company-tooltip-visible)
    (setq company-frontends '(company-echo-metadata-frontend
                              company-pseudo-tooltip-frontend-with-delay
                              company-preview-frontend))
    (define-key company-active-map [tab]
      'company-complete-selection-or-select-next-if-tooltip-visible)
    (define-key company-active-map (kbd "TAB")
      'company-complete-selection-or-select-next-if-tooltip-visible))

**Comment by jojojames** [comment]
Made the relevant changes.

Let me know if the docstrings or commit messages are not up to par yet. I could probably still use some improvement in this area. Thanks. !

**Comment by dgutov** [comment]
> You're right about wrapping company-pseudo-tooltip-unless-just-one-frontend instead. I'll get that changed.

I think the frontend's name should also be updated. Yes, it's getting long. :)

> I hook company-auto-complete to whether or not the tooltip is visible

So, what happens if you type a word, stop to think for a second, and then press SPC? I don't imagine you'd want the first completion inserted in all such circumstances.

**Comment by dgutov** [comment]
Regarding the docsrting, the first sentence  should be shorter. Using "...if appropriate..." should be fine, as long as you elaborate below. Mentioning `company-pseudo-tooltip-frontend-with-delay` in there also seems unnecessary.

Don't worry about commit messages here, I'm going to squash merge this one.

**Comment by jojojames** [comment]
> I think the frontend's name should also be updated. Yes, it's getting long. :)

You're right. I'll get that changed.

> So, what happens if you type a word, stop to think for a second, and then press SPC? I don't imagine you'd want the first completion inserted in all such circumstances.

I usually just C-g or escape out of the completion and move on. I think that might be a usability problem with company-auto-complete (it's hard not to get unexpected completions when typing fast). I think it's hard to account for all use cases like this one but maybe we can add something smarter here.

> Regarding the docsrting, the first sentence should be shorter. Using "...if appropriate..." should be fine, as long as you elaborate below. Mentioning company-pseudo-tooltip-frontend-with-delay in there also seems unnecessary.

I'll go ahead and improve the docstring further.

**Comment by dgutov** [comment]
> maybe we can add something smarter here

Maybe you can do:

```el
(defun my-company-visible-and-explicit-action-p ()
  (and (company-tooltip-visible)
       (company-explicit-action-p)))

(setq company-auto-complete #'my-company-visible-and-explicit-action-p)
```

By the way, the name of `company-tooltip-visible` should end with `-p`, too.

**Comment by jojojames** [comment]
> (defun my-company-visible-and-explicit-action-p ()
  (and (company-tooltip-visible)
       (company-explicit-action-p)))

I'll give that a shot and see.

> By the way, the name of company-tooltip-visible should end with -p, too.

Ok.


Also noticed a small bug with the popup using this delay frontend. The popup's offset is pushed to the right by 30-40 pixels instead of lining up with the prefix. I'll take a closer look at how the popup is drawn later but a step in the right direction here would be great.

**Comment by dgutov** [comment]
> The popup's offset is pushed to the right by 30-40 pixels instead of lining up with the prefix

Is it an offset the width of the prefix? Or of the overlay added by the preview?

**Comment by jojojames** [comment]
Not too sure, attaching a screenshot.

screenshot 2016-06-13 16 23 02

**Comment by dgutov** [comment]
"overlay added by the preview" looks like the correct guess. That's probably because the preview overlay is visible, and it makes the display engine think the current displayed position is at the end of it (similar to behavior described in http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18417).

The way to go about it would be to make sure the preview overlay is not visible when we're calling `company-pseudo-tooltip-show-at-point`. Maybe hide all backends and then show them again, this time including the delayed tooltip? Not sure if it's easy to program cleanly.

**Comment by jojojames** [comment]
I made the other updates.

> Maybe hide all backends and then show them again, this time including the delayed tooltip? Not sure if it's easy to program cleanly.

I was able to get some working functionality in this direction (definitely messily written). Not sure if this is directionally right or clean enough but the functionality is definitely working as far as I've tested.

    ;; post command inside company-pseudo-tooltip-unless-just-one-frontend-with-delay
    (post-command
     (if (or company-tooltip-timer
             (overlayp company-pseudo-tooltip-overlay))
         (progn
           (company-test-hide) ;; HIDE
           (company-pseudo-tooltip-unless-just-one-frontend command)
           (company-test-show)) ;; SHOW
       (setq company-tooltip-timer
             (run-with-timer company-tooltip-idle-delay nil
                             'company-pseudo-tooltip-unless-just-one-frontend-with-delay
                             'post-command))))

    (defun company-test-hide ()
      (cl-loop for frontend in company-frontends
               collect
               ;; todo account for the all the preview frontends
               (when (eq 'company-preview-frontend frontend)
                 (funcall frontend 'pre-command))))
    
    (defun company-test-show ()
      (cl-loop for frontend in company-frontends
               collect
               ;; ^todo
               (when (eq 'company-preview-frontend frontend)
                 (funcall frontend 'post-command))))

**Comment by dgutov** [comment]
If you're just checking for one frontend, this seems much shorter:

```el
(if (not (memq 'company-preview-frontend company-frontends))
    (company-pseudo-tooltip-unless-just-one-frontend command)
  (company-preview-frontend 'pre-command)
  (company-pseudo-tooltip-unless-just-one-frontend command)
  (company-preview-frontend 'post-command))
```

**Comment by jojojames** [comment]
Works like a charm for me.

**Comment by dgutov** [comment]
No need for `progn` there: the "else" branch can have multiple statements.

**Comment by jojojames** [comment]
Thanks! Let me know if there's anything else.

**Comment by dgutov** [comment]
Thanks for sticking with it!

**Comment by jojojames** [comment]
My pleasure. :)

**Comment by dgutov** [comment]
> I'll give that a shot and see.

Have you tried that yet? Or is that drawback not much of a problem?

**Comment by jojojames** [comment]
I tried it and it works pretty well.

My only minor quip about it is that I'd like to consider typing after the popup shows to be an explicit action.
That way the scenario where you type something like.

compa{cursor}

Available completions:
company-preview-frontend
company-select-next

When the completion tooltip is up, if I type all the way to company-s, I'd expect/want a space to be able to complete the rest. Maybe the explicit action is that I changed the prefix. I think the heuristic on determining when to complete is a little tricky so haven't noodled too much on it.

I think defining extra actions that can be considered explicit after the tooltip is up might solve my minor problem here.

**Comment by dgutov** [comment]
I don't want to change the meaning of "explicit action", but if you find a way to program that predicate, you can use it either way.

The idea kind of makes sense, but this way you'll also see scenarios where you are forced to press `C-g` to cancel. So I'm torn.

Looking at auto-complete, it doesn't actually do that: you can wait until the popup shows, type more to narrow the completions down, but when you press SPC, none will be inserted. It does, however, insert the first option when you press TAB.

Have you tried using `company-complete-common-or-cycle` instead of `company-select-next-if-tooltip-visible-or-complete-selection`? Or combine their logic? I think the "complete up to the common part first" step, even when the tooltip is visible, would be more faithful.

**Comment by jojojames** [comment]
I've used company-complete-common-or-cycle before, I think the main problem with it was seemingly having to tab more often in the general case. I haven't tried it with the new delay frontend but potentially something like company-complete-common-or-cycle-if-tooltip-visible-or-complete-selection might be a good solution. I think I'll play around with those options a little more and report back after.

**Comment by jojojames** [comment]
Trying something like this for my tab completion.

    (defun company-complete-common-or-cycle-if-tooltip-visible-or-complete-selection ()
      "Complete common or cycle if appropriate, or complete selection.
    Insert selection if only preview is showing or only one candidate,
    otherwise complete common or cycle."
      (interactive)
      (if (and (company-tooltip-visible-p) (> company-candidates-length 1))
          (call-interactively 'company-complete-common-or-cycle)
        (call-interactively 'company-complete-selection)))

It works fine aside from the somewhat confusing behavior of company-complete-common-or-cycle which completes up to a common prefix (expected but still confusing). Sometimes that causes behavior like:

Start typing, completion popup comes up -> press tab (expecting tab to select next candidate) -> get tab to first selection. I think it's a little too inconsistent (from a user trying to complete selections fast without thinking).

I did end up switching to using 

    (defun my-company-visible-and-explicit-action-p ()
      (and (company-tooltip-visible-p)
           (company-explicit-action-p)))

as it does get rid of that c-g edge case on first candidate.

At this point it's been a while since I've used Auto-Complete so it might be a little off faithfully but I think the current behavior at this point is more than satisfying.

**Comment by dgutov** [comment]
> the current behavior at this point is more than satisfying

Great! Thanks for reporting.

**Comment by dgutov** [comment]
> I did end up switching to using...

Should we add that to " Switching from AC" as well?

**Comment by jojojames** [comment]
Done.

**Comment by sickHamm** [comment]
@jojojames  @dgutov 

Is `company-cancel` shoud remove `company-tooltip-timer` ?

And for https://github.com/company-mode/company-mode/pull/524/commits/69687f2bac976bef81885c0fd766970bfddca591 shouldn't presume is `company-preview-frontend` preview  candidate, should use a more general way.
```
(defun company-pseudo-tooltip-unless-just-one-frontend-with-delay (command)
  "`compandy-pseudo-tooltip-frontend', but shown after a delay.
Delay is determined by `company-tooltip-idle-delay'."
  (cl-case command
    (pre-command
     (company-pseudo-tooltip-unless-just-one-frontend command)
     (when company-tooltip-timer
       (cancel-timer company-tooltip-timer)
       (setq company-tooltip-timer nil)))
    (post-command
     (if (overlayp company-pseudo-tooltip-overlay)
	 (company-pseudo-tooltip-unless-just-one-frontend command)
       (if company-tooltip-timer
	   (if (not (overlayp company-preview-overlay))
	       (progn (company-pseudo-tooltip-unless-just-one-frontend command)
		      (setq company-tooltip-timer nil))
	     (company-preview-hide)
	     (company-pseudo-tooltip-unless-just-one-frontend command)
	     (setq company-tooltip-timer nil)
	     (company-call-frontends 'post-command))
	 (setq company-tooltip-timer
	       (run-with-timer company-tooltip-idle-delay nil
			       'company-pseudo-tooltip-unless-just-one-frontend-with-delay
			       'post-command)))))
    (t
     (company-pseudo-tooltip-unless-just-one-frontend command))))
```

**Comment by jojojames** [comment]
Are you having a problem with another preview frontend?

**Pull request merged**
