### PR TITLE
Add cdlatex backend

### PR DESCRIPTION
**Pull request by benneti**
A small backend to show possible completions from [cdlatex](https://github.com/cdominik/cdlatex).

### CODE REVIEW

**Comment by dgutov** [comment]
Hi! 

I don't use Latex, so it would be non-trivial for me to maintain.

And this also depends on a third-party package, right?

Have you considered proposing a `completion-at-point-functions` element for `cdlatex-mode` instead? If said mode installs an appropriate completion function, it will automatically work with `company-mode`.

**Comment by benneti** [comment]
Hi,
Yes, it depends on cdlatex.
I did not consider this (cdlatex does not provide a completion-at-point-function), but I will have a look at it.
Do you think it is feasable/worth it to translate the company backend into a completion-at-point-function and propose a pr to cdlatex?

**Comment by dgutov** [comment]
> Do you think it is feasable/worth it to translate the company backend into a completion-at-point-function and propose a pr to cdlatex?

Yes, that's what I suggest you do.

> EDIT: after a quick look at the docs it seems like running a post-completion hook for completion-at-point-function is not as simple as it is in company or did I miss something?

It's a bit trickier (the whole `c-a-p-f` API requires more boilerplate), but as the result it should work with different completion systems, not just company-mode.

The counterpart to `post-completion` is `:exit-function`. See, for example, how it's used in `shell--command-completion-data`.

**Comment by dgutov** [comment]
Let me know if you have any further questions.

**Pull request closed without merging**
