### PR TITLE
add Julia keywords and general types.

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by dgutov** [comment]
I'm not so sure about the "general types" section; we don't list those for other languages, and they're not keywords.

Other than that, please sort the keywords alphabetically (that's what the build failure is about).

**Comment by stardiviner** [comment]
I sorted keywords with `shell-command-on-region` with `sort`, and deleted julia general types. make a force push.

**Comment by dgutov** [comment]
> make a force push.

I think you forgot to squash.

While we're on the subject of editing commits, please omit the period at the end of the commit title, and start it with a capital letter.

**Comment by stardiviner** [comment]
Those general types is from Julia type system, You can check them out at here: https://en.wikibooks.org/wiki/Introducing_Julia/Types

I don't know whether should consider them as keywords. Just because they are built-in.

**Comment by dgutov** [comment]
> I don't know whether should consider them as keywords. Just because they are built-in.

Probably not.

**Comment by stardiviner** [comment]
I see. Thanks.

**Comment by dgutov** [comment]
So, how about squashing commits together, and editing the commit message?

**Comment by stardiviner** [comment]
@dgutov I updated, squashed two commits, and edited commit message.

**Comment by dgutov** [comment]
Thanks!

**Pull request merged**
