### PR TITLE
Blank out whitespace in popups.

### PR DESCRIPTION
**Pull request by yurikhan**
I am using `whitespace-mode` to visualize whitespace:

```
$ emacs -Q
```

``` elisp
(whitespace-mode 1)
(add-to-list 'load-path "~/.emacs.d/company-mode")
(load-library "company")
(company-mode 1)
```

Now move to the end of the first line and enter `(def`.

At this point, the `company-mode` completion popup apppears. Since its background and the padding of shorter lines is drawn using spaces, they get affected by `whitespace-mode` and displayed as middle dots.

In normal editing they are fontified with a face which assigns them a very subtle color, however in `company-mode` popups they are displayed in normal popup or default face. This is distracting.

company-whitespace-before

In this patch, I force whitespace in and before `company-mode`’s popups to have foreground identical to the background, so whitespace is invisible.

company-whitespace-after

(This may require tweaking also the `:distant-foreground` face attribute on Emacs 24.5 — I haven’t yet had the chance to upgrade and so can’t test.)

### CODE REVIEW

**Comment by Alexander-Miller** [comment]
According to [this](https://www.reddit.com/r/emacs/comments/4241oy/xwidget_branch_has_been_merged_into_emacs_251/) GTK widgets can now be embedded within emacs. I've no notion of what that would realistically change, so I'm quit curious: could this be used as an alternative means to display company's popups?

**Comment by dgutov** [comment]
@Alexander-Miller Not 100% sure, but probably not.

**Comment by dgutov** [comment]
@Alexander-Miller But that's not to say that there's no way to make a better-rendered popup "soon".

`x-show-tip` has problems, but if someone was really motivated to work on a popup library based on it, and iron out the kinks (probably via bug reports to the core, and discussions, but patches to the C code would be welcome as well), it can be solved. Other approaches, like menu-based popups, should be viable as well.

**Comment by rlazoti** [comment]
I'm having exactly the same issue related by @yurikhan 
Is there any change for this PR to be merged?

**Comment by dgutov** [comment]
@rlazoti I don't think so, sorry.

**Comment by dojeda** [comment]
Urgh, scratch that. I've just realized this doesn't work. Somehow, my whitespace-mode was disabled during my testing. The idea might work if one chooses the correct function, I guess.

**Comment by dojeda** [comment]
All right, reporting back. I managed to pull it off with:
```lisp
(defvar my-prev-whitespace-mode nil)
(make-variable-buffer-local 'my-prev-whitespace-mode)
(defun pre-popup-draw ()
  "Turn off whitespace mode before showing company complete tooltip"
  (if whitespace-mode
      (progn
        (setq my-prev-whitespace-mode t)
        (whitespace-mode -1)
        (setq my-prev-whitespace-mode t))))
(defun post-popup-draw ()
  "Restore previous whitespace mode after showing company tooltip"
  (if my-prev-whitespace-mode
      (progn
        (whitespace-mode 1)
        (setq my-prev-whitespace-mode nil))))
(advice-add 'company-pseudo-tooltip-unhide :before #'pre-popup-draw)
(advice-add 'company-pseudo-tooltip-hide :after #'post-popup-draw)
```

**Comment by dgutov** [comment]
@dojeda Doesn't that make the whole window blink, with dots being removed before completion and re-added after?

**Comment by dojeda** [comment]
@dgutov : Yes, indeed. I guess that I don't mind too much because my whitespace faces are only slightly different than my regular faces. I don't think one can enable/disable minor modes on overlays...

**Comment by dgutov** [comment]
I'm going to close this PR (sorry), but see the linked issue and the new workaround I have just posted there.

**Pull request closed without merging**
