### PR TITLE
company-tng: Document post-completion and yasnippet issues

### PR DESCRIPTION
**Pull request by nikital**
Following a discussion at #881

### CODE REVIEW

**Comment by dgutov** [comment]
Thanks!

**Comment by dgutov** [comment]
Speaking of documentation, it might helpful to also mention company-tng somehow at https://github.com/company-mode/company-mode/wiki/Switching-from-AC.

**Comment by nikital** [comment]
> Speaking of documentation, it might helpful to also mention company-tng somehow at https://github.com/company-mode/company-mode/wiki/Switching-from-AC.
Does AC have company-tng-like behaviour? I thought company-tng is actually for people switching from Vim

**Comment by dgutov** [comment]
I think so?.. At least, something similar. IIRC, TAB switched between completions and made them look like they were inserted in the buffer.

But if you created a small wiki entry named "Switching From YouCompleteMe" instead, I also wouldn't mind. Just a few sentences there might suffice.

**Comment by nikital** [comment]
https://github.com/company-mode/company-mode/wiki/Switching-from-Vim

**Comment by dgutov** [comment]
Thanks, that title is okay too.

Is the Gif made from Vim screen capture, though?

**Pull request merged**
