### PR TITLE
Mention just enabled Discussions

### PR DESCRIPTION
**Pull request by yugaego**
Discussed in #1134.

See example of a pinned [Before Asking a Question](https://github.com/yugaego/tmp/discussions). 

Updated `README.md` may serve as a replacement to an earlier suggested `Question / Feature Request` one-entry-point issue template, that provided a link to `Discussions`. 

Note that `Ask a Question` currently links to the 1st post in the Discussions. This would work fine if the first post would have a content such as:

```
#### Before asking a question
1. Read [installation and usage information](http://company-mode.github.io).
2. Read `C-h f company-mode` documentation.
3. Review [Wiki articles](https://github.com/company-mode/company-mode/wiki/Tips-&-tricks).
4. Search in [existing issues](https://github.com/company-mode/company-mode/issues?q=) and [discussions](https://github.com/yugaego/tmp/discussions).

Post [third-party packages](https://github.com/company-mode/company-mode/wiki/Third-Party-Packages) questions to the maintainers of the respective packages.

If you have **general `Emacs` questions**
1. Consult `C-h r` Emacs manual.
2. Search on [EmacsWiki](https://www.emacswiki.org/emacs), [Reddit](https://www.reddit.com/r/emacs/), [Emacs.SE](https://emacs.stackexchange.com).
3. Send an email to the [help-gnu-emacs](https://lists.gnu.org/mailman/listinfo/help-gnu-emacs) mailing list.
```

### CODE REVIEW

**Comment by dgutov** [comment]
Thanks!

The Discussions are enabled now. Could you post that question? I'd like to preserve the authorship.

**Comment by yugaego** [comment]
> Could you post that question? I'd like to preserve the authorship.

Sure, just did it, with some welcoming pre-wording added. Feel free to correct or suggest a correction.
I also considered adding

Welcome to `Company` and `Emacs` [free software](https://www.gnu.org/philosophy/free-sw.html) community!

but wasn't sure that'd be fully appropriate/desirable.

On a test repo I pinned and locked the post (editorial tools should be on the right side of the post) to make it outstanding.

> Note that Ask a Question currently links to the 1st post in the Discussions

I made a mistake here. The numbering is common with the Issues and PRs.

I'll submit a PR to fix this with maybe other README minor text corrections.

**Comment by yugaego** [comment]
BTW, your suggestion to add `r/emacs` and `Emacs.SE` was a real good one.
Probably you had seen it, according to the [2020 survey](https://emacssurvey.org/2020/) 73.9% and 44.8% of the respondents repsectively chose them for answering the question *"What Emacs community forums have you visited in the past year"*.
With a decent 3rd place given to the mailing list by 24.4% of the answers.

**Comment by dgutov** [comment]
> but wasn't sure that'd be fully appropriate/desirable

I... don't know. Either works for me.

> On a test repo I pinned and locked the post (editorial tools should be on the right side of the post) to make it outstanding.

I've pinned the post but didn't lock it. Perhaps we'll get some useful responses? If not, I'll clean and lock it later.

> I'll submit a PR to fix this with maybe other README minor text corrections.

:+1: 

> Probably you had seen it, according to the 2020 survey 73.9% and 44.8% of the respondents repsectively chose them for answering the question "What Emacs community forums have you visited in the past year".

Yup. :-)

**Comment by yugaego** [comment]
> Either works for me.

Added that "Emacs free software" phrase then.

> I've pinned the post but didn't lock it. Perhaps we'll get some useful responses?

Great idea 👍🏻

**Comment by dgutov** [comment]
Speaking of checklists before asking a question, Magit seems to have a nice one on the before-new-issue page: https://github.com/magit/magit/issues/new/choose

**Comment by yugaego** [comment]
Ha! And look at those fancy links. Appears it's possible via `config.yml` settings.
I dreamt of eventually adding question/feature-request issue template with the link to `Discussions`, and the `Magit` example demonstrates a perfect way achieving it.
Would you be willing to add it yourself or rather get my input on the checkboxes/links?

**Comment by dgutov** [comment]
Your input is certainly welcome. I'm a little busy these days, so let's see who gets around to it first! :+1:

**Comment by yugaego** [comment]
> Your input is certainly welcome. I'm a little busy these days, so let's see who gets around to it first! 👍

Okay, I'm on it then.

**Pull request merged**
