### PR TITLE
Async no cache flicker

### PR DESCRIPTION
**Pull request by dgutov**
* Internal handling of input interruption with throw-catch that ensures completion is not aborted.
* An interface to opt into `while-no-input` for company-capf which reuses the mechanism.
* As an semi-private feature, the completion table can just `(throw 'interrupted 'new-input)` instead, if it detects new input using its own methods.

~I suppose the main thing left to decide is whether `while-no-input` should be opt-in or opt-out for the capf backend.~

EDIT: just opt-out: see NEWS.

### CODE REVIEW

**Comment by dgutov** [comment]
@yyoncho @kiennq I think you might be interested in this too, we discussed this kind of solution back in https://github.com/emacs-lsp/lsp-mode/issues/1894, and this moves the same approach inside company-mode.

**Comment by dgutov** [comment]
@minad With the new info that Emacs 29's version of Eglot [can misbehave](https://github.com/joaotavora/eglot/discussions/1127#discussioncomment-7698442) inside `while-no-input` it seems I'll have to make this opt-in, at least until that version of Emacs becomes obsolete enough.

Though if you had some clever workaround for it, I'm happy to consider it as an alternative.

BTW, have you seen any similar reports from the lsp-mode side as well?

**Comment by minad** [comment]
> Though if you had some clever workaround for it, I'm happy to consider it as an alternative.

Why not simply detect the Eglot Capf and Eglot version? This would be a trivial fix.

**Comment by dgutov** [comment]
Do you keep around the CAPF function that produced the current completion table? It's when querying it we'd have to decide whether to allow interruptions.

Also, regarding the version check -- any preference? The below is not free

```lisp
(benchmark-run 1 (find-library-name "eglot") (lm-version))
```

...although almost of the time is spent in `find-library-name`.

**Comment by minad** [comment]
> Do you keep around the CAPF function that produced the current completion table?

No. I don't have such a workaround in Corfu. I recommend to fix broken Capfs via Cape *manually*.

> Also, regarding the version check -- any preference? The below is not free

As a cheaper alternative you could check `emacs-major-version` only. Or use `package-get-version`.

**Comment by dgutov** [comment]
> No. I don't have such a workaround in Corfu. I recommend to fix broken Capfs via Cape manually.

I'd like to, but that seems bad for the OotB experience. If only it had been ELPA-only, then we wouldn't be talking about this now.

> As a cheaper alternative you could check emacs-major-version only. Or use package-get-version.

`package-get-version` works if I bind `buffer-file-name` appropriately, but that's what the call to `find-library-name` returns in my example above. The expensive one.

**Pull request merged**
