### PR TITLE
Fix invalid use of string match

### PR DESCRIPTION
**Pull request by juergenhoetzel**
In *fsharp-mode* with [*company-backend* ](https://github.com/fsharp/emacs-fsharp-mode/blob/master/fsharp-mode-completion.el)completion of this source

```F#
[<EntryPoint>]
let main argv =
    printfn "%A" argv.[
```

triggers

```
  Debugger entered--Lisp error: (invalid-regexp "Unmatched [ or [^")
  string-match("[" ".")
  ...
  company-auto-complete-p("[")
  company--continue-failed(stop)
  company--continue()
  company--perform()
  company-post-command()
```

### CODE REVIEW

**Comment by dgutov** [comment]
Have you tried just using `regexp-quote`?

**Comment by juergenhoetzel** [comment]
> Have you tried just using regexp-quote?

Yes, Actually I started with `regexp-quote` but thought above commit is more readable.

**Comment by dgutov** [comment]
I'd prefer the former version then, thanks.

**Comment by juergenhoetzel** [comment]
> I'd prefer the former version then, thanks.

No problem: Amended.

**Comment by dgutov** [comment]
Thanks!

**Pull request merged**
